// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8NGM4Qz0DD8D5XXdM6H9aHBSiiL6CoTc',
    appId: '1:836946022184:web:73db61724efaa12f264a1d',
    messagingSenderId: '836946022184',
    projectId: 'flutternotes2024',
    authDomain: 'flutternotes2024.firebaseapp.com',
    storageBucket: 'flutternotes2024.appspot.com',
    measurementId: 'G-MWMPCVFM5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRStgpfaL7btsvGLz3hETUWX9hCGpzqQI',
    appId: '1:836946022184:android:a459cdb5b2ee897b264a1d',
    messagingSenderId: '836946022184',
    projectId: 'flutternotes2024',
    storageBucket: 'flutternotes2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoGKLSknqDaoTDAdWzBixpEXoSCght_D8',
    appId: '1:836946022184:ios:b8e1764eef5a40ce264a1d',
    messagingSenderId: '836946022184',
    projectId: 'flutternotes2024',
    storageBucket: 'flutternotes2024.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoGKLSknqDaoTDAdWzBixpEXoSCght_D8',
    appId: '1:836946022184:ios:b8e1764eef5a40ce264a1d',
    messagingSenderId: '836946022184',
    projectId: 'flutternotes2024',
    storageBucket: 'flutternotes2024.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8NGM4Qz0DD8D5XXdM6H9aHBSiiL6CoTc',
    appId: '1:836946022184:web:e7874e7443eb111b264a1d',
    messagingSenderId: '836946022184',
    projectId: 'flutternotes2024',
    authDomain: 'flutternotes2024.firebaseapp.com',
    storageBucket: 'flutternotes2024.appspot.com',
    measurementId: 'G-R9TGLQ5697',
  );
}
